'''
Problem statement:
A TikTok user has a username represented by a string of lowercase English letters, username. The user wants to transform their username to explore possible variations. The user can perform the following operations on the username multiple times, in any order:
• Replace an occurrence of 'cc' with 'a'.
• Replace an occurrence of 'dd' with 'b'.
The user may also choose not to apply any operations, leaving the username unchanged.
Given the string username, determine the total number of distinct usernames that can be generated by applying these transformations. Since the result can be large, return the total count modulo 109+7.
Example
username = "ccc"
The possible usernames that can be generated are:
• "ccc" → "ac"
• "ccc" → "ca"
• "ccc" (No operation is applied)
Hence the answer is 3.
'''

'''
Initialize dp array with given input size
If the string is empty then there is only one possibility to get user name
Iteratively check if last string have 'cc' or 'dd' and update dp accordingly
Fill in the dp array in such a way what if we have given username of length 3, what if we have given username of lenght 4 and so on until end and fill dp array
'''

def countUserNames(username):
    mod=10**9+7
    n=len(username)
    dp=[0]*(n+1)
    
    dp[0]=1 #If we have empty string we can form one username
    dp[1]=dp[0] #According to problem we need to have min len of username to be 2 to replace
    
    for i in range(2,n+1):
        dp[i]=dp[i-1]
        if username[i-2:i]=='cc':
            dp[i]=(dp[i]+dp[i-2])%mod
        if username[i-2:i]=='dd':
            dp[i]=(dp[i]+dp[i-2])%mod
    return dp[n]

if __name__=="__main__":
    test=[('ccddaccdd',16),('ddcccadfa',6),('ddccdgaded',4)]
    for t,e in test:
        if countUserNames(t)==e:
            print(f'test case passed for input {t} and output is{e}')
        
        